# This file implements the user's correct suggestion to use the official Firebase Hosting action.

name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}'
          projectId: workflow-central
